version = 1
SPDX-PackageName = "Hello World WoW Addon"
SPDX-PackageDownloadLocation = "https://github.com/pinged-eu/wow-addon-helloworld"
SPDX-PackageSupplier = "DS/2, Dirk Strauss"

# Your project sources
[[annotations]]
path = [
"embeds.xml",
"assets/**",
"options/**",
"Locales/**",
"epgp/**",
"Libs/downloadAceLibs.ps1",
"raid-log-window/**",
"HelloWorld*",
"settings.lua",
"install.develop.ps1",
]
precedence = "closest"
SPDX-FileCopyrightText = "DS/2, Dirk Strauss"
SPDX-License-Identifier = "GPL-3.0-or-later"

# external ace3 lib
[[annotations]]
path = [
"Libs/Ace3/**",
]
precedence = "closest"
SPDX-FileCopyrightText = "Ace3 Development Team"
# technically this is not a BSD4 license since the ace team added at point 3 a disclaimer to not use this product as standalone. Apart from that it is a BSD4 license.
SPDX-License-Identifier = "BSD-4-Clause"

# Documentations and Configs
[[annotations]]
path = [
  "**/*.adoc",
  "**/*.md",
  "**/*.1",
  "docs/**",
  "examples/**",
  ".changelogs/*",
  "os-packaging/linux/**",
]
SPDX-FileCopyrightText = "DS/2, Dirk Strauss"
SPDX-License-Identifier = "CC-BY-SA-4.0"

# Autogenerated files and configs
[[annotations]]
path = [
  "poetry.lock",
  "go.sum",
  "CRUSH.md",
  "AGENTS.md",
  "Makefile",
  "Cargo.lock",
  "REUSE.toml",
  "**/.containerignore",
  "**/.dockerignore",
  ".semver-version",
  ".licenserc.yaml",
  ".gitlab-ci.yml",
  ".gitattributes",
  ".gitignore",
  ".pre-commit-config.yaml",
  ".pre-commit-check-config.yaml",
  "requirements.txt",
  ".editorconfig",
  "renovate.json",
  ".devcontainer.json",
  ".vscode/**",
  ".github/**",
  ".gitlab/**",
  "cliff.toml",
  "rustfmt.toml",
  "config.toml",
  "rust-toolchain.toml",
  "dagger.json",
  ".cargo/config.toml",
  ".bazeliskrc",
  ".bazelrc",
  ".bazelversion",
  "WORKSPACE.bazel",
  "MODULE.bazel",
  "MODULE.bazel.lock",
  "**/BUILD.bazel",
  "**/BUILD.bazel.lock",
  "Dockerfile.dapper",
  ".jj/**",
  ".crush/**",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
