= Development of this Addon

Just to be clear: this is just learning stuff. So don't expect this to be the next BigWigs or DBM.

You can directly work with this project from https://vscode.dev/github/pinged-eu/wow-addon-helloworld[inside a browser].

include::development.installation.adoc[leveloffset=+1]

== Branch names

The main branch is the develop branch where all the WoW Retail stuff is actively developed.
This also includes updating the TOC to the latest PTR build.

Final deployable releases however are on their respective addon name branch:

* dragonflight = the releases for WoW v10 DragonFlight
* wotlk = the releases for WoW v3 Wrath of the Lich King
* cataclysm = the releases for WoW v4 Cataclysm
* mop = the releases for WoW v5 Mists of Pandaria
* thewarwithin = the releases for WoW v11 The War Within

To use the `git flow` feature, you can run this command to initialize it (while on the develop branch):

[,shell]
----
git flow init --feature=feat/ --bugfix=fix/ --release=release/ --tag="v"
----

The "next release" branch is _develop_.
The production release branch is _thewarwithin_

== Creating new features

Run:

[,shell]
----
git flow feature start <feature-name>
----

Perform your changes and commit them. Push it to the remote repository:

[,shell]
----
git push origin <feature-name>
----

To manually merge it into the develop branch:

[,shell]
----
git flow feature finish <feature-name>
----

NOTE: This should be done automatically by the CI/CD pipeline after some review.

== Adding fixes

Fixes should be done against the current live branch (say, thewarwithin currently). The branch name must be fix/FIXNAMEORID. It should be applied against the current live branch, as well as the develop branch.

include::localization.adoc[leveloffset=+1]

== Adding new translations

Translations should be done against the current live branch (say, thewarwithin currently). The branch name must be i18n/TRANSLATIONNAMEORID. It should be applied against the current live branch, as well as the develop branch.

include::localization.adoc[leveloffset=+1]
