name: build commit

on:
  push:
  workflow_call:

jobs:
  license-check:
    name: license check
    runs-on: ubuntu-24.04
    steps:
      - name: checkout branch
        uses: actions/checkout@v7
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v6
  j1:
    name: build addon
    needs: license-check
    runs-on: windows-2025
    env:
      ZIPFILENAME: "helloworld-addon.zip"
    steps:
      - name: checkout branch
        uses: actions/checkout@v7
      - name: clean and prepare
        run: |
          Remove-Item -Recurse helloworld -ErrorAction Ignore
          Remove-Item $Env:ZIPFILENAME -ErrorAction Ignore
      - name: create tmp zip dir
        run: |
          $loc = Get-Location
          New-Item -ItemType directory -Path $loc -Name helloworld -Force
          Copy-Item -Recurse -Path $loc\* -Destination .\helloworld -Include "*.toc","*.lua"
      - name: Package
        run: Compress-Archive -DestinationPath $Env:ZIPFILENAME -CompressionLevel Fastest -LiteralPath "helloworld"
      - name: show dir
        run: dir
      - uses: actions/upload-artifact@v7
        with:
          name: ${{env.ZIPFILENAME}}
          path: helloworld/
          if-no-files-found: error
          retention-days: 1
