name: build commit

on:
  push:
    # branches:
    #   - main
    #   - develop

jobs:
  j1:
    runs-on: windows-2022
    steps:
      - name: checkout branch
        uses: actions/checkout@v2
      - name: create tmp zip dir
        run: |
          md helloworld
          Copy-Item -Recurse -Path .\* -Destination helloworld -Filter "*.toc","*.lua" -Verbose
      - name: Archive Release
        uses: thedoctor0/zip-release@0.6.2
        with:
          type: 'zip'
          filename: "helloworld-addon.zip"
          exclusions: '!helloworld'
      - name: show dir
        run: dir
      - uses: actions/upload-artifact@v3
        with:
          path: helloworld-addon.zip
          if-no-files-found: error
          retention-days: 1
