name: build commit

on:
  push:
    tags-ignore:
      - "v*"
  workflow_call:

jobs:
  license-check:
    name: license check
    runs-on: ubuntu-24.04
    steps:
      - name: checkout branch
        uses: actions/checkout@v7
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v6
  j1:
    name: build alpha addon
    needs: license-check
    runs-on: ubuntu-24.04
    steps:
      - name: checkout branch
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Package (alpha, no upload)
        uses: BigWigsMods/packager@v2
        with:
          args: -d
      - uses: actions/upload-artifact@v7
        with:
          name: helloworld-addon-alpha
          path: .release/*.zip
          if-no-files-found: error
          retention-days: 14
