name: Create release on tag

on:
  push:
    tags:
      - "*-alpha-*"

jobs:
  j2:
    name: create release on windows
    runs-on: windows-2022
    steps:
      - name: "Determine tag"
        run: "echo \"RELEASE_TAG=${GITHUB_REF#refs/tags/}\" >> $GITHUB_ENV"
      - name: checkout tag
        uses: actions/checkout@v2
      - name: build addon

      - name: create github release
        if: 
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "release.tar.gz,foo/*.txt"
          bodyFile: "body.md"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: show dir
        run: dir
